### ISSUE TITLE
About claim "aggregation_uri"

### ISSUE THREAD

**Issue by Denisthemalice** [oauth-wg/draft-ietf-oauth-status-list#255]
In #228, C2bo wrote:

> The claim "aggregation_uri" is meant as a way to allow efficient caching for RPs, not for alternative URIs 
> - it points to all relevant status lists for an issuer or specific referenced token type.

"aggregation_uri" is defined in 4.1 as:

> aggregation_uri: OPTIONAL.  JSON String that contains a URI to retrieve the Status List Aggregation for this type of Referenced Token.  
See section 9 for further detail.

Section 9 (Status List Aggregation) states:

> Status List Aggregation is an optional mechanism to retrieve a list of URIs to all Status List Tokens, allowing a Relying Party to fetch all relevant Status Lists for a specific type of Referenced Token or Issuer.  

These two descriptions are not aligned with section 4.1. **The case of the Issuer is not mentioned in section 4.1**.
However, in section 9, the sentence mentions: 
> all relevant Status Lists for a specific type of Referenced Token **or Issuer**.  

 Then comes some questions.

How can the Relying party retrieve either: 

a) all relevant Status Lists for a specific [type of] Referenced Token, or
b) all relevant Status Lists for an Issuer ?

In the first case, how long should "all relevant Status Lists" for a specific type of Referenced Token be accessible ? 
Same question for "all relevant Status Lists" for an Issuer.

If the case of the "Issuer" is indeed supported, there should be some additional text to warn the Issuers about some consequences when this claim is supported. For example:

> "All relevant Status Lists for an Issuer" allows a Relying Party to know how many Referenced Tokens have been issued by an Issuer and are either valid, suspended or revoked at an instant of time. This can reveal also the number of entities that have been registered. Issuers should be warned of the consequences before choosing to support this optional claim.

Finally, the argument is that this claim is "meant as a way to allow efficient caching for RPs". However, I still have difficulties to understand the usefulness of this optional claim when the JSON String contains a URI to retrieve the Status List Aggregation for this Referenced Token.
Caching is pretty well supported by the ttl claim:

> *  ttl: OPTIONAL.  The ttl (time to live) claim, if present, MUST specify the maximum amount of time, in seconds, that the Status List Token can be cached by a consumer before a fresh copy SHOULD be retrieved.

**Comment by paulbastian** [comment]
- Your first point was already fixed in the newest version
- its up to the Issuer/Status List Provider how long he provides these, no need for any normative text
- your reference to the privacy is also mentioned in the current draft already, you posted this already twice now, so I'm repeating my answer here: https://drafts.oauth.net/draft-ietf-oauth-status-list/draft-ietf-oauth-status-list.html#name-observability-of-outsiders
- the `ttl` claim usage is already well explained in the draft: https://drafts.oauth.net/draft-ietf-oauth-status-list/draft-ietf-oauth-status-list.html#name-status-list-caching

Pending close as there are no new issues reported.

**Comment by Denisthemalice** [comment]
OK. Section 4.1 is now consistent with Section 9.

However, I still have difficulties to understand the usefulness of this optional claim and I still cant' understand the following sentence: 

> the argument is that this claim is "meant as a way to allow efficient caching for RPs".

An additional side question: 

How can a Relying Party retrieve :

a) either all relevant Status Lists for a specific [type of] Referenced Token,
b) or all relevant Status Lists for an Issuer ?

**Comment by paulbastian** [comment]
Imagine that a Relying Party doesn't want to pull the Status List Token ad-hoc during presentation but already wants it ready to use and regularly pull all of the necessary ones together. This may be beneficial for performance and for offline capability. A police officer may want to fetch all mDL status lists in the morning if he may drive in an area without internet connectivity.

**Comment by Denisthemalice** [comment]
No response has been provided to my question which was:

> How can a Relying Party retrieve :
> (a) either all relevant Status Lists for a specific [type of] Referenced Token,
> (b) or all relevant Status Lists for an Issuer ?

I understand the case (b) but not the case (a).

I can't understand the rational for this sentence (and I believe that this topic is related to my previous comment about the case (a)):

>    If a Relying Party encounters an invalid Status List referenced in the response from the Status List Aggregation endpoint, 
>    it SHOULD continue processing the other valid Status Lists referenced in the response.

There should be one and only one SLT which contains the status of the Referenced Token. 
So why continue to processing the other valid Status Lists referenced in the response ?

Let us now suppose that mDLs has been issued by a country to 20 millions of drivers. 
How many SLTs would need to be referenced ? Quite a lot. 

In issue #220, I wrote: 
> a "CRL issuer" can use several "distribution points". Why should it be otherwise for a "Status Issuer" ?

The mDL is a nice example to illustrate the fact that, at least, two URIs should be made available. 
The Police can use a private address to fetch the appropriate SLT on a network that is not open to the public, 
while commercial web servers can use a different (public) address to fetch the same the appropriate SLT.
 If an issuing country is a member of the EU, it can provide a URI in the domain name of the country, e.g. de or fr, 
as well as in the domain mane of the eu. 

If more that one SLT distribution point is available, this number will be multiplied by the number of SLT distribution points.  
This can overload the SLTs. However, if one or more base URIs are negotiated between the Issuer and the Status Issuer 
for each SLT distribution point, these base URIs can be included into the aggregation_uri. 

Then, each base URI will contain a list of relative URIs for each SLT. 

A further advantage is the fact that the content of the aggregation_uri extension will remain the same, even when a new SLT is added.

To summarize, the idea would be to issue all SLTs under a set of base URIs where each SLT will be placed under a single 
(and same) relative URI.

I am conscious that this would be an important change to the current content of the draft, but it would provide major benefits.

**Comment by c2bo** [comment]
> > If a Relying Party encounters an invalid Status List referenced in the response from the Status List Aggregation endpoint,
> > it SHOULD continue processing the other valid Status Lists referenced in the response.
> 
> There should be one and only one SLT which contains the status of the Referenced Token. So why continue to processing the other valid Status Lists referenced in the response ?

To provide a bit of context for that section: "This mechanism is intended to support fetching and caching mechanisms and allow offline validation of the status of a reference token for a period of time."

The intention of 

> If a Relying Party encounters an invalid Status List referenced in the response from the Status List Aggregation endpoint, it SHOULD continue processing the other valid Status Lists referenced in the response.

is that RPs that want to cache Status List Tokens (e.g., because they want to have them available for offline usage later), should continue to parse entries in the aggregation_uri if they encounter an error - don't fail and terminate all parsing, but keep on fetching and verifying the other entries.

----

> This can overload the SLTs. However, if one or more base URIs are negotiated between the Issuer and the Status Issuer
for each SLT distribution point, these base URIs can be included into the aggregation_uri.

Most modern systems deal with that deployment complexity afaik not by providing more URLs, but by load balancing via DNS: the same DNS entry resolves depending on load and geographical(/network) proximity to other IPs (or other deployments/clusters). That is at least my experience and the main reason why I don't think it is necessary to add the complexity of having more than one entry in the aggregation_uri.

We also allow for redirects when resolving Status List Tokens, which would easily allow to shift traffic to another URL if it becomes necessary (outages etc).

----

> The mDL is a nice example to illustrate the fact that, at least, two URIs should be made available. The Police can use a private address to fetch the appropriate SLT on a network that is not open to the public, while commercial web servers can use a different (public) address to fetch the same the appropriate SLT. If an issuing country is a member of the EU, it can provide a URI in the domain name of the country, e.g. de or fr, as well as in the domain mane of the eu.

There is no reason for the private address to be visible anywhere publicly in that example is there? In that example I would see the public aggregation_uri as the one URI that is made publicly available and any other system can provide its own mechanism for distribution (e.g., via a private network etc), but there is no reason to include that information somewhere publicly.

**Comment by Denisthemalice** [comment]
C2bo wrote: 

> If a Relying Party encounters an invalid Status List referenced in the response from the Status List Aggregation endpoint, it SHOULD continue processing the other valid Status Lists referenced in the response.

is that RPs that want to cache Status List Tokens (e.g., because they want to have them available for offline usage later), should continue to parse entries in the aggregation_uri if they encounter an error - don't fail and terminate all parsing, but keep on fetching and verifying the other entries.

===================================================================================

I am sorry, but I still don't understand. What do you mean by " if they encounter an error" ? The normal way is to use the uri that is contained in the Referenced Token and then to use the index to get the appropriate status. Since there is one distribution point there can only be a single SLT which will be the more up-to-date. 

===================================================================================

C2bo also wrote: 

> This can overload the SLTs. However, if one or more base URIs are negotiated between the Issuer and the Status Issuer
for each SLT distribution point, these base URIs can be included into the aggregation_uri.

Most modern systems deal with that deployment complexity afaik not by providing more URLs, but by load balancing via DNS: the same DNS entry resolves depending on load and geographical(/network) proximity to other IPs (or other deployments/clusters). That is at least my experience and the main reason why I don't think it is necessary to add the complexity of having more than one entry in the aggregation_uri.

===================================================================================
Section 9 (Status List Aggregation) starts with:

> Status List Aggregation is an optional mechanism to retrieve **_a list of URIs_** (...)

This means that aggregation_uri can contain several entries.

However, this is in contradiction with section 4.1 which states:

> aggregation_uri: OPTIONAL. JSON String that **_contains a URI_** to retrieve the Status List Aggregation for this type of Referenced Token or Issuer.

Why are there two cases, i.e., "this type of Referenced Token or Issuer" ? 

I still don't understand the first case.

I can understand the second case, where the Relying Party would like to cache in advance all the SLTs from a given Issuer 
as soon as it got a Referenced Token. But in that case, it would be a single **_base uri_** (instead of a list of uris). 

===================================================================================

> The mDL is a nice example to illustrate the fact that, at least, two URIs should be made available. The Police can use a private address to fetch the appropriate SLT on a network that is not open to the public, while commercial web servers can use a different (public) address to fetch the same the appropriate SLT. (...)

C2bo wrote: 

> There is no reason for the private address to be visible anywhere publicly in that example is there? In that example I would see the public aggregation_uri as the one URI that is made publicly available and any other system can provide its own mechanism for distribution (e.g., via a private network etc), but there is no reason to include that information somewhere publicly.

Thank you for the explanations and for the rational. Your last sentence allowed me to bounce. 
Let us continue to use the mDL example. Two distribution points would be used:
-	a public distribution point for the public, and
-	a private distribution point for the police.

The private distribution point for the police would no be included into the Referenced Token, but is only known by the police. 

The public distribution point can contain a uri with a SLT with 2 bits.
The private distribution point can contain a uri with a SLT with 8 bits.

In the second case, the police can know various statuses of the mDL (but not the public). For example:

- this mDL allows to drive cars,
- this mDL allows to drive trucks,
- this mDL allows to drive school buses,
- this mDL has been suspended because the driver got 12 or more penalty points.
- this mDL has been invalidated following a decision of the police or of a court

To summarize : 

The Status Issuer can use several distribution points, but a single public distribution point will be indicated in the Referenced Token.
Each SLT can use a different number of bits (1, 2, 4 or 8 bits)

**Comment by c2bo** [comment]
I think there is some misunderstanding on how the `aggregation_uri` currently works:
It is a uri that is provided either by metadata (.well-known etc) or within a Status List Token itself. When resolved, it contains a JSON array with a list of URLs to Status List Tokens. Those are the relevant Status List Tokens within that scope (either all Status List Tokens that the issuer is serving, or all Status List Tokens relevant for that credential type). 

From that context:
> If they encounter an error ...

The aggregation_uri contains a list of Status List Tokens - if fetching or validating one of them fails, the others should still be processed

> I can understand the second case, where the Relying Party would like to cache in advance all the SLTs from a given Issuer
as soon as it got a Referenced Token. But in that case, it would be a single base uri (instead of a list of uris).

Depending on size, there could be more than 1 Status List Token for a credential (referenced token) type, so `aggregation_uri` even if scoped to one referenced token type could point to a list. 

The idea of embedding `aggregation_uri` also in the Status List Token itself is to provide an option to ecosystems that do not (or do not want to) use other ways of metadata like .well-known - that way it is sort of self-contained without other dependencies: a RP can always fetch one Status List Token after receiving a Referenced Token and get `aggregation_uri` from there to cache all relevant Status List Tokens.

**Comment by Denisthemalice** [comment]
> I think there is some misunderstanding on how the aggregation_uri currently works:
> It is a uri that is provided either by metadata (.well-known etc) or within a Status List Token itself. 
> When resolved, it contains a JSON array with a list of URLs to Status List Tokens. 

This now becomes understandable, but this is not what the text was saying:

> JSON String that contains a URI to retrieve the Status List Aggregation for this type of Referenced Token or Issuer.

> Those are the relevant Status List Tokens within that scope (either all Status List Tokens that the issuer is serving, 
or all Status List Tokens relevant for that credential type).`

The term "credential type" is not present in the draft. This is still not understandable. There is no means to understand what the "scope" is. 

> The aggregation_uri contains a list of Status List Tokens - if fetching or validating one of them fails, 
> the others should still be processed

This is still not understandable to me. The status of a Referenced Token is provided by the latest published SLT. 
At a given point of time and for a given Referenced Token, only the latest SLT is published. 
If the SLT has been malformed or is not correctly signed, then this is a fatal error. 
If the SLT cannot be retrieved, then trying more times is likely to succeed.

> Depending on size, there could be more than 1 Status List Token for a credential (referenced token) type, 
so aggregation_uri even if scoped to one referenced token type could point to a list.

Depending of the size of "what" ? 

> "there could be more than 1 Status List Token". 

This statement would need to be explained in details.

What is a "credential type" ?

> ... so aggregation_uri even if scoped to one referenced token type could point to a list.

The end of this sentence is not understandable to me.

**Comment by paulbastian** [comment]
> > I think there is some misunderstanding on how the aggregation_uri currently works:
> > It is a uri that is provided either by metadata (.well-known etc) or within a Status List Token itself.
> > When resolved, it contains a JSON array with a list of URLs to Status List Tokens.
> 
> This now becomes understandable, but this is not what the text was saying:
> 
> > JSON String that contains a URI to retrieve the Status List Aggregation for this type of Referenced Token or Issuer.

This text is from the draft an clear enough to me. What's missing?

> 
> > Those are the relevant Status List Tokens within that scope (either all Status List Tokens that the issuer is serving,
> > or all Status List Tokens relevant for that credential type).`
> 
> The term "credential type" is not present in the draft. This is still not understandable. There is no means to understand what the "scope" is.


This text is not in the draft and just an attempt of explanation within this issue, therefore it makes sense that these terms are not in the draft. I think the text is good enough, otherwise make a proposal (as you now understand the concept) or we close the issue.

> 
> > The aggregation_uri contains a list of Status List Tokens - if fetching or validating one of them fails,
> > the others should still be processed
> 
> This is still not understandable to me. The status of a Referenced Token is provided by the latest published SLT. At a given point of time and for a given Referenced Token, only the latest SLT is published. If the SLT has been malformed or is not correctly signed, then this is a fatal error. If the SLT cannot be retrieved, then trying more times is likely to succeed.

There may be more than one "latest" Status List Token, if the Status Issuer is chunking these Referenced Tokens into multiple Status Lists for scalability. Therefore, aggregation_uri may contain multiple URIs to multiple Status List Tokens. If one of them fails for whatever reason, still continue with the others.

> 
> > Depending on size, there could be more than 1 Status List Token for a credential (referenced token) type,
> > so aggregation_uri even if scoped to one referenced token type could point to a list.
> 
> Depending of the size of "what" ?
> 
> > "there could be more than 1 Status List Token".
> 
> This statement would need to be explained in details.
> 
> What is a "credential type" ?
> 
> > ... so aggregation_uri even if scoped to one referenced token type could point to a list.
> 
> The end of this sentence is not understandable to me.

This is explained here: https://drafts.oauth.net/draft-ietf-oauth-status-list/draft-ietf-oauth-status-list.html#section-13.3-3

**Comment by Denisthemalice** [comment]
>  I think there is some misunderstanding on how the aggregation_uri currently works:
>  It is a uri that is provided either by metadata (.well-known etc) or within a Status List Token itself.
>  When resolved, it contains a JSON array with a list of URLs to Status List Tokens.

> This now becomes understandable, but this is not what the text was saying:

> JSON String that contains a URI to retrieve the Status List Aggregation for this type of Referenced Token or Issuer.

> This text is from the draft an clear enough to me. What's missing?

The draft is unclear as it does not contain the following wording: 

> "JSON array with a list of URLs to Status List Tokens.

Some text like below would be more understandable:

> uri that is provided either by metadata (.well-known etc) or within a Status List Token itself.
When resolved, it contains a JSON array with a list of URLs to Status List Tokens.

You wrote:

> There may be more than one "latest"  Status List Token, if the Status Issuer is chunking these Referenced Tokens into multiple Status Lists for scalability. Therefore, aggregation_uri may contain multiple URIs to multiple Status List Tokens. If one of them fails for whatever reason, still continue with the others.

The above explanation is using the word "chunking": 

> "if the Status Issuer is chunking these Referenced Tokens into multiple Status Lists for scalability".

 I made a search on the term "chunk" and, in the draft, I found the following text:

>    The Status List Issuer may chunk its Referenced Tokens into multiple
>    Status Lists to reduce the transmission size of an individual Status
>    List Token.  This may be useful for setups where some entities
>    operate in constrained environments, e.g. for mobile internet or
>    embedded devices.  The Status List Issuer may chunk the Status List
>    Tokens depending on the Referenced Token's expiry date to align their
>    lifecycles and allow for easier retiring of Status List Tokens,
>    however the Status Issuer must be aware of possible privacy risks due
>    to correlations.

"chunk" is a term I am not familiar with. 
         Cambridge dictionary: a part of something, especially a large part. 
         North American: divide (something) into chunks. 

This does not help me to understand why "chunking" is used and what is being "chunked".

The Issuer can decide to place THE status of a Referenced Token in any SLT depending upon a criteria of its is own choice. 
It is is NOT the job of the Status List Issuer to decide: it is the job of the Issuer. 

This still does not explain why THE status of a Referenced Token should be placed into "more than one SLT". 
To make an analogy, when using CRLs, there is one and only one (base) CRL referenced in an X.509 PKC and if it fails 
(whatever the verb "fail" may mean) then there is no "continuation". 

Let us make things simple and do not attempt to make things over complicated.

The text that is "chunk-related" should be removed.

The text that is mentioning "types of Referenced Tokens" should also be removed.

**Comment by paulbastian** [comment]
> > I think there is some misunderstanding on how the aggregation_uri currently works:
> > It is a uri that is provided either by metadata (.well-known etc) or within a Status List Token itself.
> > When resolved, it contains a JSON array with a list of URLs to Status List Tokens.
> 
> > This now becomes understandable, but this is not what the text was saying:
> 
> > JSON String that contains a URI to retrieve the Status List Aggregation for this type of Referenced Token or Issuer.
> 
> > This text is from the draft an clear enough to me. What's missing?
> 
> The draft is unclear as it does not contain the following wording:
> 
> > "JSON array with a list of URLs to Status List Tokens.
> 
> Some text like below would be more understandable:
> 
> > uri that is provided either by metadata (.well-known etc) or within a Status List Token itself.
> > When resolved, it contains a JSON array with a list of URLs to Status List Tokens.

No, you still got it wrong. The Status List contains ONE URL in the `aggregation_uri`, that one points to the object described in Section 9 which contains the array of URLs to the other Status List Tokens.

> 
> You wrote:
> 
> > There may be more than one "latest"  Status List Token, if the Status Issuer is chunking these Referenced Tokens into multiple Status Lists for scalability. Therefore, aggregation_uri may contain multiple URIs to multiple Status List Tokens. If one of them fails for whatever reason, still continue with the others.
> 
> The above explanation is using the word "chunking":
> 
> > "if the Status Issuer is chunking these Referenced Tokens into multiple Status Lists for scalability".
> 
> I made a search on the term "chunk" and, in the draft, I found the following text:
> 
> > The Status List Issuer may chunk its Referenced Tokens into multiple
> > Status Lists to reduce the transmission size of an individual Status
> > List Token.  This may be useful for setups where some entities
> > operate in constrained environments, e.g. for mobile internet or
> > embedded devices.  The Status List Issuer may chunk the Status List
> > Tokens depending on the Referenced Token's expiry date to align their
> > lifecycles and allow for easier retiring of Status List Tokens,
> > however the Status Issuer must be aware of possible privacy risks due
> > to correlations.
> 
> "chunk" is a term I am not familiar with. Cambridge dictionary: a part of something, especially a large part. North American: divide (something) into chunks.
> 
> This does not help me to understand why "chunking" is used and what is being "chunked".
> 
> The Issuer can decide to place THE status of a Referenced Token in any SLT depending upon a criteria of its is own choice. It is is NOT the job of the Status List Issuer to decide: it is the job of the Issuer.
> 
> This still does not explain why THE status of a Referenced Token should be placed into "more than one SLT". To make an analogy, when using CRLs, there is one and only one (base) CRL referenced in an X.509 PKC and if it fails (whatever the verb "fail" may mean) then there is no "continuation".
> 
> Let us make things simple and do not attempt to make things over complicated.
> 
> The text that is "chunk-related" should be removed.
> 
> The text that is mentioning "types of Referenced Tokens" should also be removed.

I'm ok to rename "chunk" into "aggregate".

**Comment by Denisthemalice** [comment]
It seems that we don't agree about the role of the Issuer and of the Status Issuer.
It is the Issuer that decides which SLT will be used for a given Referenced Token (i.e., it is not the Status Issuer).

I still disagree with (or do not understadd) the following sentence: 

> The aggregation_uri contains a list of Status List Tokens - if fetching or validating one of them fails,
> the others should still be processed

In addition, would you agree to remove the text that is mentioning "types of Referenced Tokens" ?

**Comment by paulbastian** [comment]
How the Status List Tokens are organized is primarily a technical task, therefore the Status List Issuer's. As the recommendation is anyway to randomize, there is no need for the Issuer of Referenced Token to give further guidance.

I also don't agree to remove the text types of Referenced Tokens. Easy example: A goverment issuer is issuing multiple Credentials/Referenced Token, but police officers are only interested to cache the status information for driving licenses. Therefore it may make sense to have multiple Status List Aggregations per Referenced Token.

**Comment by paulbastian** [comment]
I added further explanations for aggregation_uri and renamed chunking in #272 
If you still disagree after this, please bring it up to the mailing list or bring it up in the IETF Bangkok meeting
